export const mealRan =

{
    "meals": [
        {
            "idMeal": "53026",
            "strMeal": "Tamiya",
            "strDrinkAlternate": null,
            "strCategory": "Vegetarian",
            "strArea": "Egyptian",
            "strInstructions": "oak the beans in water to cover overnight.Drain. If skinless beans are unavailable, rub to loosen the skins, then discard the skins. Pat the beans dry with a towel.\r\nGrind the beans in a food mill or meat grinder.If neither appliance is available, process them in a food processor but only until the beans form a paste. (If blended too smoothly, the batter tends to fall apart during cooking.) Add the scallions, garlic, cilantro, cumin, baking powder, cayenne, salt, pepper, and coriander, if using.  Refrigerate for at least 30 minutes.\r\nShape the bean mixture into 1-inch balls.Flatten slightly and coat with flour.\r\nHeat at least 1½-inches of oil over medium heat to 365 degrees.\r\nFry the patties in batches, turning once, until golden brown on all sides, about 5 minutes.Remove with a wire mesh skimmer or slotted spoon. Serve as part of a meze or in pita bread with tomato-cucumber salad and tahina sauce.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg",
            "strTags": null,
            "strYoutube": "https://www.youtube.com/watch?v=mulqW-J3Yy4",
            "strIngredient1": "Broad Beans",
            "strIngredient2": "Spring Onions",
            "strIngredient3": "Garlic Clove",
            "strIngredient4": "Parsley",
            "strIngredient5": "Cumin",
            "strIngredient6": "Baking Powder",
            "strIngredient7": "Cayenne Pepper",
            "strIngredient8": "Flour",
            "strIngredient9": "Vegetable Oil",
            "strIngredient10": "",
            "strIngredient11": "",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "3 cups ",
            "strMeasure2": "6",
            "strMeasure3": "4",
            "strMeasure4": "1/4 cup",
            "strMeasure5": "2 tsp",
            "strMeasure6": "1 tsp ",
            "strMeasure7": "1/2 tsp",
            "strMeasure8": "Spinkling",
            "strMeasure9": "As required",
            "strMeasure10": " ",
            "strMeasure11": " ",
            "strMeasure12": " ",
            "strMeasure13": " ",
            "strMeasure14": " ",
            "strMeasure15": " ",
            "strMeasure16": " ",
            "strMeasure17": " ",
            "strMeasure18": " ",
            "strMeasure19": " ",
            "strMeasure20": " ",
            "strSource": "https://oukosher.org/recipes/tamiya-egyptian-dried-fava-bean-fritters/",
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        },
        {
            "idMeal": "52907",
            "strMeal": "Duck Confit",
            "strDrinkAlternate": null,
            "strCategory": "Miscellaneous",
            "strArea": "French",
            "strInstructions": "The day before you want to make the dish, scatter half the salt, half the garlic and half of the herbs over the base of a small shallow dish. Lay the duck legs, skin-side up, on top, then scatter over the remaining salt, garlic and herbs. Cover the duck and refrigerate overnight. This can be done up to 2 days ahead.\r\nPour the wine into a saucepan that will snugly fit the duck legs in a single layer. Brush the salt off the duck legs and place them, skin-side down, in the wine. Cover the pan with a lid and place over a medium heat. As soon as the wine starts to bubble, turn the heat down to the lowest setting and cook for 2 hours, checking occasionally that the liquid is just barely simmering. (If you own a heat diffuser, it would be good to use it here.) After 2 hours, the duck legs should be submerged in their own fat and the meat should feel incredibly tender when prodded. Leave to cool.\r\nThe duck legs are now cooked and can be eaten immediately – or you can follow the next step if you like them crisp. If you are preparing ahead, pack the duck legs tightly into a plastic container or jar and pour over the fat, but not the liquid at the bottom of the pan. Cover and leave in the fridge for up to a month, or freeze for up to 3 months. The liquid you are left with makes a tasty gravy, which can be chilled or frozen until needed.\r\nTo reheat and crisp up the duck legs, heat oven to 220C/fan 200C/gas 7. Remove the legs from the fat and place them, skin-side down, in an ovenproof frying pan. Roast for 30-40 mins, turning halfway through, until brown and crisp. Serve with the reheated gravy, a crisp salad and some crisp golden ptoatoes.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/wvpvsu1511786158.jpg",
            "strTags": null,
            "strYoutube": "https://www.youtube.com/watch?v=MHhLJqghY-o",
            "strIngredient1": "Sea Salt",
            "strIngredient2": "Bay Leaf",
            "strIngredient3": "Garlic",
            "strIngredient4": "Thyme",
            "strIngredient5": "Duck Legs",
            "strIngredient6": "White Wine",
            "strIngredient7": "",
            "strIngredient8": "",
            "strIngredient9": "",
            "strIngredient10": "",
            "strIngredient11": "",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "Handful",
            "strMeasure2": "4",
            "strMeasure3": "4 cloves",
            "strMeasure4": "Handful",
            "strMeasure5": "4",
            "strMeasure6": "100ml",
            "strMeasure7": "",
            "strMeasure8": "",
            "strMeasure9": "",
            "strMeasure10": "",
            "strMeasure11": "",
            "strMeasure12": "",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "https://www.bbcgoodfood.com/recipes/2085/barneys-confit-of-duck",
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        },
        {
            "idMeal": "53055",
            "strMeal": "Cevapi Sausages",
            "strDrinkAlternate": null,
            "strCategory": "Beef",
            "strArea": "Croatian",
            "strInstructions": "Place the ground meat in a bowl. Chop the onion very finely and grate the garlic cloves. Add to the bowl. Add the chopped parsley, all sorts of paprika, baking soda, dried breadcrumbs, water, Vegeta, salt, and pepper.\r\nMix well with the hand mixer fitted with the dough hooks. Cover the bowl with cling film/ plastic foil and leave to rest for 1 or 2 hours in the refrigerator.\r\nTake portions of the meat mixture, about 50-55 g/ 1.7-1.9 oz/ ¼ cup portions, and form the cevapi. The rolls should be about as thick as your thumb and about 7-10 cm/ 3-4 inches long. I had 18 sausages. The recipe can be easily doubled.\r\nGrill the cevapcici on the hot grill pan or on the barbecue for about 12-14 minutes, turning them several times in between, or until brown and cooked through. I checked by cutting one in the middle and then grilling the following batches for the same period of time.\r\nServe hot as suggested above. The cevapcici can be reheated in the oven at 180 degrees Celsius/ 350 degrees Fahrenheit for about 10 minutes or until heated through. Check one, if it is not hot enough, give the sausages a few more minutes.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/vc08jn1628769553.jpg",
            "strTags": "Sausages",
            "strYoutube": "https://www.youtube.com/watch?v=_MpSxSgS7f8",
            "strIngredient1": "Minced Beef",
            "strIngredient2": "Minced Pork",
            "strIngredient3": "Onion",
            "strIngredient4": "Garlic",
            "strIngredient5": "Parsley",
            "strIngredient6": "Paprika",
            "strIngredient7": "Baking Powder",
            "strIngredient8": "Breadcrumbs",
            "strIngredient9": "Water",
            "strIngredient10": "Vegetable Stock Cube",
            "strIngredient11": "Salt",
            "strIngredient12": "Pepper",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "500g",
            "strMeasure2": "250g",
            "strMeasure3": "1",
            "strMeasure4": "4 cloves",
            "strMeasure5": "3 tblsp chopped",
            "strMeasure6": "1 tbs",
            "strMeasure7": "3/4 teaspoon",
            "strMeasure8": "2 tbs",
            "strMeasure9": "3 tbs",
            "strMeasure10": "1",
            "strMeasure11": "1 tsp ",
            "strMeasure12": "1 tsp ",
            "strMeasure13": " ",
            "strMeasure14": " ",
            "strMeasure15": " ",
            "strMeasure16": " ",
            "strMeasure17": " ",
            "strMeasure18": " ",
            "strMeasure19": " ",
            "strMeasure20": " ",
            "strSource": "https://whereismyspoon.co/cevapi-or-cevapcici-recipe-grilled-sausages-croatian-food/",
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        },
        {
            "idMeal": "52862",
            "strMeal": "Peach & Blueberry Grunt",
            "strDrinkAlternate": null,
            "strCategory": "Dessert",
            "strArea": "American",
            "strInstructions": "Heat oven to 190C/170C fan/gas 5. Butter a wide shallow ovenproof dish. Blend the cornflour with the orange zest and juice, and put in a large pan with the sugar. Halve, stone and slice the peaches and add to the pan. Bring slowly to the boil, stirring gently until the sauce is shiny and thickened, about 3-4 mins. Remove from the heat, stir in the blueberries and tip into the prepared dish.\r\nTip the flour into a mixing bowl and add the 50g butter. Rub the butter into the flour until it resembles fine breadcrumbs, then stir in half the sugar. Mix the remaining sugar with the cinnamon and set aside.\r\nAdd the milk to the dry ingredients and mix to a soft dough. Turn out onto a lightly floured surface and knead briefly. Roll out to an oblong roughly 16 x 24cm. Brush with melted butter and sprinkle evenly with the spicy sugar. Roll up from one long side and cut into 12 slices. Arrange around the top of the dish, leaving the centre uncovered.\r\nBake for 20-25 mins, until the topping is crisp and golden. Serve warm.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/ssxvup1511387476.jpg",
            "strTags": "Desert,Pudding,Fruity",
            "strYoutube": "https://www.youtube.com/watch?v=SNeO28BCpsc",
            "strIngredient1": "Corn Flour",
            "strIngredient2": "Orange",
            "strIngredient3": "Orange",
            "strIngredient4": "Caster Sugar",
            "strIngredient5": "Peaches",
            "strIngredient6": "Blueberries",
            "strIngredient7": "Self-raising Flour",
            "strIngredient8": "Butter",
            "strIngredient9": "Muscovado Sugar",
            "strIngredient10": "Cinnamon",
            "strIngredient11": "Milk",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "1 tsp ",
            "strMeasure2": "Juice of 2",
            "strMeasure3": "Zest of 1",
            "strMeasure4": "2 tbs",
            "strMeasure5": "6",
            "strMeasure6": "250g",
            "strMeasure7": "200g",
            "strMeasure8": "50g",
            "strMeasure9": "100g ",
            "strMeasure10": "1 tsp ",
            "strMeasure11": "6 tblsp",
            "strMeasure12": "",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "https://www.bbcgoodfood.com/recipes/1553651/peach-and-blueberry-grunt",
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        },
        {
            "idMeal": "52853",
            "strMeal": "Chocolate Avocado Mousse",
            "strDrinkAlternate": null,
            "strCategory": "Dessert",
            "strArea": "British",
            "strInstructions": "1. Blend all the mousse ingredients together in your food processor until smooth. Add the cacao powder first and, as you blend, have all the ingredients to hand in order to adjust the ratios slightly as the size of avocados and bananas varies so much. The perfect ratio in order to avoid the dish tasting too much of either is to use equal amounts of both.\r\n\r\n2. Taste and add a few drops of stevia if you feel you need more sweetness.\r\n\r\n3. Fill little cups or shot glasses with the mousse, sprinkle with the cacao powder or nibs and serve.\r\n\r\nTip If you don’t have a frozen banana to hand you can just use a normal one and then chill the mousse before serving for a cooling dessert.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/uttuxy1511382180.jpg",
            "strTags": null,
            "strYoutube": "https://www.youtube.com/watch?v=wuZffe60q4M",
            "strIngredient1": "Banana",
            "strIngredient2": "Cacao",
            "strIngredient3": "Avocado",
            "strIngredient4": "Honey",
            "strIngredient5": "Lemon Juice",
            "strIngredient6": "Vanilla",
            "strIngredient7": "Water",
            "strIngredient8": "Sea Salt",
            "strIngredient9": "",
            "strIngredient10": "",
            "strIngredient11": "",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "1",
            "strMeasure2": "3 tbsp",
            "strMeasure3": "1",
            "strMeasure4": "2 tblsp ",
            "strMeasure5": "1 tsp ",
            "strMeasure6": "1 tsp ",
            "strMeasure7": "2 tbsp",
            "strMeasure8": "pinch",
            "strMeasure9": "",
            "strMeasure10": "",
            "strMeasure11": "",
            "strMeasure12": "",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "http://www.hemsleyandhemsley.com/recipe/chocolate-avocado-mousse/",
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        },
        {
            "idMeal": "52939",
            "strMeal": "Callaloo Jamaican Style",
            "strDrinkAlternate": null,
            "strCategory": "Miscellaneous",
            "strArea": "Jamaican",
            "strInstructions": "Cut leaves and soft stems from the kale branches, them soak in a bowl of cold water for about 5-10 minutes or until finish with prep.\r\nProceed to slicing the onions, mincing the garlic and dicing the tomatoes. Set aside\r\nRemove kale from water cut in chunks.\r\nPlace bacon on saucepan and cook until crispy. Then add onions, garlic, thyme, stir for about a minute or more\r\nAdd tomatoes; scotch bonnet pepper, smoked paprika. Sauté for about 2-3 more minutes.\r\nFinally add vegetable, salt, mix well, and steamed for about 6-8 minutes or until leaves are tender. Add a tiny bit of water as needed. Adjust seasonings and turn off the heat.\r\nUsing a sharp knife cut both ends off the plantain. This will make it easy to grab the skin of the plantains. Slit a shallow line down the long seam of the plantain; peel only as deep as the peel. Remove plantain peel by pulling it back.\r\nSlice the plantain into medium size lengthwise slices and set aside.\r\nCoat a large frying pan with cooking oil spray. Spray the tops of the plantains with a generous layer of oil spray and sprinkle with salt, freshly ground pepper.\r\nLet the plantains \"fry\" on medium heat, shaking the frying pan to redistribute them every few minutes.\r\nAs the plantains brown, continue to add more cooking oil spray, salt and pepper (if needed) until they have reached the desired color and texture.\r\nRemove and serve with kale",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/ussyxw1515364536.jpg",
            "strTags": "Savory",
            "strYoutube": "https://www.youtube.com/watch?v=bCr3GasJWwE",
            "strIngredient1": "Kale",
            "strIngredient2": "Bacon",
            "strIngredient3": "Garlic",
            "strIngredient4": "Onion",
            "strIngredient5": "Paprika",
            "strIngredient6": "Thyme",
            "strIngredient7": "Tomato",
            "strIngredient8": "Red Pepper",
            "strIngredient9": "Banana",
            "strIngredient10": "Vegetable Oil",
            "strIngredient11": "",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "1  bunch",
            "strMeasure2": "2 strips",
            "strMeasure3": "3 cloves Chopped",
            "strMeasure4": "1 medium",
            "strMeasure5": "1/2 tsp",
            "strMeasure6": "1 Sprig",
            "strMeasure7": "1",
            "strMeasure8": "1",
            "strMeasure9": "4",
            "strMeasure10": "Splash",
            "strMeasure11": "",
            "strMeasure12": "",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "https://www.africanbites.com/callaloo-jamaican-style/",
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        },
        {
            "idMeal": "53038",
            "strMeal": "Mustard champ",
            "strDrinkAlternate": null,
            "strCategory": "Side",
            "strArea": "Irish",
            "strInstructions": "STEP 1\r\nBoil the potatoes for 15 mins or until tender. Drain, then mash.\r\n\r\nSTEP 2\r\nHeat the milk and half the butter in the corner of the pan, then beat into the mash, along with the wholegrain mustard.\r\n\r\nSTEP 3\r\nGently fry the spring onions in the remaining butter for 2 mins until just soft but still a perky green. Fold into the mash and serve. Great with gammon or to top a fish pie.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/o7p9581608589317.jpg",
            "strTags": null,
            "strYoutube": "https://www.youtube.com/watch?v=_iKllHSC978",
            "strIngredient1": "Potatoes",
            "strIngredient2": "Milk",
            "strIngredient3": "Butter",
            "strIngredient4": "Mustard",
            "strIngredient5": "Spring Onions",
            "strIngredient6": "Spring Onions",
            "strIngredient7": "",
            "strIngredient8": "",
            "strIngredient9": "",
            "strIngredient10": "",
            "strIngredient11": "",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "1kg",
            "strMeasure2": "200ml",
            "strMeasure3": "50g",
            "strMeasure4": "2 tbs",
            "strMeasure5": "Bunch",
            "strMeasure6": "Bunch",
            "strMeasure7": " ",
            "strMeasure8": " ",
            "strMeasure9": " ",
            "strMeasure10": " ",
            "strMeasure11": " ",
            "strMeasure12": " ",
            "strMeasure13": " ",
            "strMeasure14": " ",
            "strMeasure15": " ",
            "strMeasure16": " ",
            "strMeasure17": " ",
            "strMeasure18": " ",
            "strMeasure19": " ",
            "strMeasure20": " ",
            "strSource": "https://www.bbcgoodfood.com/recipes/mustard-champ",
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        },
        {
            "idMeal": "52813",
            "strMeal": "Kentucky Fried Chicken",
            "strDrinkAlternate": null,
            "strCategory": "Chicken",
            "strArea": "American",
            "strInstructions": "Preheat fryer to 350°F. Thoroughly mix together all the spice mix ingredients.\r\nCombine spice mix with flour, brown sugar and salt.\r\nDip chicken pieces in egg white to lightly coat them, then transfer to flour mixture. Turn a few times and make sure the flour mix is really stuck to the chicken. Repeat with all the chicken pieces.\r\nLet chicken pieces rest for 5 minutes so crust has a chance to dry a bit.\r\nFry chicken in batches. Breasts and wings should take 12-14 minutes, and legs and thighs will need a few more minutes. Chicken pieces are done when a meat thermometer inserted into the thickest part reads 165°F.\r\nLet chicken drain on a few paper towels when it comes out of the fryer. Serve hot.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/xqusqy1487348868.jpg",
            "strTags": "Meat,Spicy",
            "strYoutube": "https://www.youtube.com/watch?v=PTUxCvCz8Bc",
            "strIngredient1": "Chicken",
            "strIngredient2": "Oil",
            "strIngredient3": "Egg White",
            "strIngredient4": "Flour",
            "strIngredient5": "Brown Sugar",
            "strIngredient6": "Salt",
            "strIngredient7": "paprika",
            "strIngredient8": "onion salt",
            "strIngredient9": "chili powder",
            "strIngredient10": "black pepper",
            "strIngredient11": "celery salt",
            "strIngredient12": "sage",
            "strIngredient13": "garlic powder",
            "strIngredient14": "allspice",
            "strIngredient15": "oregano",
            "strIngredient16": "basil",
            "strIngredient17": "marjoram",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "1 whole",
            "strMeasure2": "2 quarts neutral frying",
            "strMeasure3": "1",
            "strMeasure4": "1 1/2 cups ",
            "strMeasure5": "1 tablespoon",
            "strMeasure6": "1 tablespoon",
            "strMeasure7": "1 tablespoon",
            "strMeasure8": "2 teaspoons",
            "strMeasure9": "1 teaspoon",
            "strMeasure10": "1 teaspoon",
            "strMeasure11": "1/2 teaspoon",
            "strMeasure12": "1/2 teaspoon",
            "strMeasure13": "1/2 teaspoon",
            "strMeasure14": "1/2 teaspoon",
            "strMeasure15": "1/2 teaspoon",
            "strMeasure16": "1/2 teaspoon",
            "strMeasure17": "1/2 teaspoon",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "http://www.tablespoon.com/recipes/copycat-kfc-original-style-chicken/97c93d14-9d8c-4bc7-96dc-1e0b37e4fcaa",
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        },
        {
            "idMeal": "52908",
            "strMeal": "Ratatouille",
            "strDrinkAlternate": null,
            "strCategory": "Vegetarian",
            "strArea": "French",
            "strInstructions": "Cut the aubergines in half lengthways. Place them on the board, cut side down, slice in half lengthways again and then across into 1.5cm chunks. Cut off the courgettes ends, then across into 1.5cm slices. Peel the peppers from stalk to bottom. Hold upright, cut around the stalk, then cut into 3 pieces. Cut away any membrane, then chop into bite-size chunks.\r\nScore a small cross on the base of each tomato, then put them into a heatproof bowl. Pour boiling water over the tomatoes, leave for 20 secs, then remove. Pour the water away, replace the tomatoes and cover with cold water. Leave to cool, then peel the skin away. Quarter the tomatoes, scrape away the seeds with a spoon, then roughly chop the flesh.\r\nSet a sauté pan over medium heat and when hot, pour in 2 tbsp olive oil. Brown the aubergines for 5 mins on each side until the pieces are soft. Set them aside and fry the courgettes in another tbsp oil for 5 mins, until golden on both sides. Repeat with the peppers. Don’t overcook the vegetables at this stage, as they have some more cooking left in the next step.\r\nTear up the basil leaves and set aside. Cook the onion in the pan for 5 mins. Add the garlic and fry for a further min. Stir in the vinegar and sugar, then tip in the tomatoes and half the basil. Return the vegetables to the pan with some salt and pepper and cook for 5 mins. Serve with basil.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/wrpwuu1511786491.jpg",
            "strTags": "Vegetables,SideDish",
            "strYoutube": "https://www.youtube.com/watch?v=BFdQUgAFtGU",
            "strIngredient1": "Aubergine",
            "strIngredient2": "Courgettes",
            "strIngredient3": "Yellow Pepper",
            "strIngredient4": "Tomato",
            "strIngredient5": "Olive Oil",
            "strIngredient6": "Basil",
            "strIngredient7": "Onion",
            "strIngredient8": "Garlic Clove",
            "strIngredient9": "Red Wine Vinegar",
            "strIngredient10": "Sugar",
            "strIngredient11": "",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "2 large",
            "strMeasure2": "4",
            "strMeasure3": "2",
            "strMeasure4": "4 large",
            "strMeasure5": "5 tbs",
            "strMeasure6": "Bunch",
            "strMeasure7": "1 medium",
            "strMeasure8": "3 finely chopped",
            "strMeasure9": "1 tsp ",
            "strMeasure10": "1 tsp ",
            "strMeasure11": "",
            "strMeasure12": "",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "https://www.bbcgoodfood.com/recipes/2903/ratatouille",
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        },
        {
            "idMeal": "53035",
            "strMeal": "Ham hock colcannon",
            "strDrinkAlternate": null,
            "strCategory": "Pork",
            "strArea": "Irish",
            "strInstructions": "STEP 1\r\nPeel and cut the potatoes into even, medium-sized chunks. Put in a large pan filled with cold salted water, bring to the boil and cook for 10-15 mins until a knife can be inserted into the potatoes easily.\r\n\r\nSTEP 2\r\nMeanwhile, melt the butter in a large sauté pan over a medium heat. Add the garlic, cabbage, spring onions and some seasoning. Stir occasionally until the cabbage is wilted but still retains a little bite, then set aside.\r\n\r\nSTEP 3\r\nDrain the potatoes, leave to steam-dry for a couple of mins, then mash with the cream, mustard and seasoning in the same saucepan. Stir in the cabbage and ham hock. Keep warm over a low heat.\r\n\r\nSTEP 4\r\nReheat the pan you used to cook the cabbage (no need to wash first), add a splash of oil, crack in the eggs and fry to your liking. To serve, divide the colcannon between bowls and top each with a fried egg.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/n41ny81608588066.jpg",
            "strTags": null,
            "strYoutube": "https://www.youtube.com/watch?v=aQJAU2iJ730",
            "strIngredient1": "Floury Potatoes",
            "strIngredient2": "Butter",
            "strIngredient3": "Garlic Clove",
            "strIngredient4": "Cabbage",
            "strIngredient5": "Spring Onions",
            "strIngredient6": "Double Cream",
            "strIngredient7": "Mustard",
            "strIngredient8": "Ham",
            "strIngredient9": "Eggs",
            "strIngredient10": "",
            "strIngredient11": "",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "800g",
            "strMeasure2": "50g",
            "strMeasure3": "3 chopped",
            "strMeasure4": "1 chopped",
            "strMeasure5": "8",
            "strMeasure6": "100ml",
            "strMeasure7": "2 tbs",
            "strMeasure8": "180g",
            "strMeasure9": "4",
            "strMeasure10": " ",
            "strMeasure11": " ",
            "strMeasure12": " ",
            "strMeasure13": " ",
            "strMeasure14": " ",
            "strMeasure15": " ",
            "strMeasure16": " ",
            "strMeasure17": " ",
            "strMeasure18": " ",
            "strMeasure19": " ",
            "strMeasure20": " ",
            "strSource": "https://www.bbcgoodfood.com/recipes/ham-hock-colcannon",
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        }
    ]
}